# Generated by Django 3.2 on 2021-06-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('SubCode', models.CharField(max_length=10)),
                ('Department', models.CharField(choices=[('Computer Science & Engineering', 'Computer Science & Engineering'), ('Information Technology', 'Information Technology')], max_length=30)),
                ('Date', models.DateField()),
                ('Url', models.URLField(blank=True)),
            ],
        ),
    ]
