# Generated by Django 3.2 on 2021-05-23 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appRelease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='releaseDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apprelease',
            name='appFile',
            field=models.FileField(upload_to='release/'),
        ),
    ]
