# Generated by Django 2.2.7 on 2021-05-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRelease', '0002_auto_20210523_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprelease',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
