# Generated by Django 3.2 on 2021-05-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
    ]
