# Generated by Django 3.2 on 2021-05-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='name',
            new_name='signatory',
        ),
    ]
