# Generated by Django 3.1 on 2020-09-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classdetail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='classdetails',
            new_name='classdetail',
        ),
    ]
