# Generated by Django 3.1 on 2020-09-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdetail', '0002_auto_20200906_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetail',
            name='meetid',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='classdetail',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
