# Generated by Django 3.1 on 2020-09-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdetail', '0003_auto_20200907_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetail',
            name='subteach',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='classdetail',
            name='meetid',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='classdetail',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
