# Generated by Django 3.1 on 2020-09-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdetail', '0004_auto_20200908_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetail',
            name='classgroup',
            field=models.CharField(default='3334', max_length=4),
        ),
    ]
