# Generated by Django 3.1.4 on 2020-12-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdetail', '0005_classdetail_classgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='classdetailcs3132',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subcode', models.CharField(max_length=10)),
                ('subteach', models.CharField(default='N/A', max_length=30)),
                ('classgroup', models.CharField(default='3334', max_length=4)),
                ('url', models.URLField(blank=True)),
                ('meetid', models.CharField(blank=True, max_length=13)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='classdetail',
            new_name='classdetailcs3334',
        ),
    ]
