# Generated by Django 3.1.4 on 2020-12-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdetail', '0006_auto_20201209_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetailcs3132',
            name='classgroup',
            field=models.CharField(default='3132', max_length=4),
        ),
    ]
