# Generated by Django 3.1.7 on 2021-04-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdetail', '0007_auto_20201210_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='classdetailcs4142',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subcode', models.CharField(max_length=10)),
                ('subteach', models.CharField(default='N/A', max_length=30)),
                ('classgroup', models.CharField(default='3132', max_length=4)),
                ('url', models.URLField(blank=True)),
                ('meetid', models.CharField(blank=True, max_length=13)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='classdetailcs4344',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subcode', models.CharField(max_length=10)),
                ('subteach', models.CharField(default='N/A', max_length=30)),
                ('classgroup', models.CharField(default='3132', max_length=4)),
                ('url', models.URLField(blank=True)),
                ('meetid', models.CharField(blank=True, max_length=13)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='classdetailcs45',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subcode', models.CharField(max_length=10)),
                ('subteach', models.CharField(default='N/A', max_length=30)),
                ('classgroup', models.CharField(default='3132', max_length=4)),
                ('url', models.URLField(blank=True)),
                ('meetid', models.CharField(blank=True, max_length=13)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
