# Generated by Django 3.2 on 2021-05-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdetail', '0009_auto_20210408_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='classdetailit4142',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subcode', models.CharField(max_length=10)),
                ('subteach', models.CharField(default='N/A', max_length=60)),
                ('classgroup', models.CharField(default='4142', max_length=4)),
                ('url', models.URLField(blank=True)),
                ('meetid', models.CharField(blank=True, max_length=13)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='classdetailit4344',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subcode', models.CharField(max_length=10)),
                ('subteach', models.CharField(default='N/A', max_length=60)),
                ('classgroup', models.CharField(default='4344', max_length=4)),
                ('url', models.URLField(blank=True)),
                ('meetid', models.CharField(blank=True, max_length=13)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
